# Begin Project
project:
  type: tutorial-template
  # FYI: the tutorial-template project type is defined in the lmu-osc/tutorial-template extension
# End Project

# Begin Website
repo-url: https://github.com/lmu-osc/Simulations-for-Advanced-Power-Analyses
website:
  title: "Simulations for Advanced Power Analyses"
  page-footer:
    border: false
    center: © 2023 Felix Schönbrodt, Moritz Fischer. Published by LMU Open Science Center. Licensed under CC BY-SA 4.0.
  repo-url: https://github.com/lmu-osc/Simulations-for-Advanced-Power-Analyses

  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/lmu-osc/Simulations-for-Advanced-Power-Analyses
          - text: Report a Bug
            href: https://github.com/lmu-osc/Simulations-for-Advanced-Power-Analyses/issues
      - icon: house-heart
        url: https://www.osc.lmu.de/

  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Models"
        contents:
          - lm1.qmd
          - lm2.qmd
          - glm.qmd
          - lmm.qmd
          - sem.qmd
      - section: "Bonuses"
        contents:
          - optimizing-code.qmd
          - how-many-iterations.qmd
          - sem-fit-index.qmd
      - resources.qmd
# End Website

# Begin Includes
include-in-header:
  - file: matomo-analytics.html
# End Includes

# Begin Format
# use only if needed. the default format for `tutorial-template` projects is tutorial-template-html+tutorial
# we recommend just extending the definition below if you need to make format changes
format:
  tutorial-template-html+tutorial:
    css:
      - footer/footer-style.css
    include-after-body:
      - file: footer/footer.html
# End Format

execute:
  freeze: auto
  cache: true

# Begin Editor
editor: source
# End Editor

bibliography: references.bib
