{
  "hash": "e1430349a85668541e04f405335d7694",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bonus: Optimizing R code for speed\"\nauthor: \"Felix Schönbrodt\"\naliases: [optimizing_code.html]\n---\n\n*Reading/working time: ~30 min.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Preparation: Install and load all necessary packages\n# install.packages(c(\"RcppArmadillo\", \"future.apply\"))\n\nlibrary(RcppArmadillo) # for fast LMs\nlibrary(future.apply) # for parallel processing\n\n# plan() initializes parallel processing,\n# for faster code execution\n# By default, it uses all available cores\nplan(multisession)\n```\n:::\n\n\n\nOptimizing code for speed can be an art -- and you get lost and spend/waste hours by micro-optimizing some milliseconds. But the Pareto principle applies here: With 20% effort, you can have quick and substantial gains.\n\n*Code profiling* means that the code execution is timed, just like you had a stopwatch. Your goal is to make your code snippet as fast as possible. RStudio has a [built-in profiler](https://support.posit.co/hc/en-us/articles/218221837-Profiling-R-code-with-the-RStudio-IDE) that (in theory) allows to see which code line takes up the longest time. But in my experience, if the computation of each single line is very short (and the duration mostly comes from the many repetitions), it is very inaccurate (i.e., the time spent is allocated to the wrong lines). Therefore, we'll resort to the simplest way of timing code: We will measure overall execution time by wrapping our code in a `system.time({ ... })` call. Longer code blocks need to be wrapped in curly braces `{...}`. The function returns multiple timings; the relevant number for us is the \"elapsed\" time. This is also called the \"wall clock\" time -- the time you actually have to wait until computation finished.\n\n\n# First, naive version\n\nHere is a first version of the power simulation code for a simple LM. Let's see how long it takes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt0 <- system.time({\n  iterations <- 5000\n  ns <- seq(300, 500, by = 50)\n  result <- data.frame()\n\n  for (n in ns) {\n    p_values <- c()\n\n    for (i in 1:iterations) {\n      treatment <- c(rep(0, n / 2), rep(1, n / 2))\n      BDI <- 23 - 3 * treatment + rnorm(n, mean = 0, sd = sqrt(117))\n      df <- data.frame(treatment, BDI)\n      res <- lm(BDI ~ treatment, data = df)\n      p_values <- c(\n        p_values,\n        summary(res)$coefficients[\"treatment\", \"Pr(>|t|)\"]\n      )\n    }\n\n    result <- rbind(\n      result,\n      data.frame(n = n, power = sum(p_values < .005) / iterations)\n    )\n  }\n})\nt0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   user  system elapsed \n  6.831   0.074   7.140 \n```\n\n\n:::\n\n```{.r .cell-code}\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    n  power\n1 300 0.3424\n2 350 0.4180\n3 400 0.4918\n4 450 0.5506\n5 500 0.6044\n```\n\n\n:::\n:::\n\n\nThis first version takes 7.14 seconds. Of course we have sampling error here as well; if you run this code multiple times, you will always get slightly different timings. But, again, we refrain from micro-optimizing in the millisecond range, so a single run is generally good enough. You should only tune your simulation in a way that it takes at least a few seconds; if you are in the millisecond range, the timings are imprecise and you won't see speed improvements very well.\n\n# Rule 1: No growing vectors/data frames\n\nThis is one of the most common bottlenecks: You start with an empty vector (or even worse, a data frame) and grow it by `rbind`-ing new rows to it in each iteration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt1 <- system.time({\n  iterations <- 5000\n  ns <- seq(300, 500, by = 50)\n\n  result <- data.frame()\n\n  for (n in ns) {\n    # print(n)   # uncomment to see progress\n\n    # CHANGE: Preallocate vector with the final size, initialize with NAs\n    p_values <- rep(NA, iterations)\n\n    for (i in 1:iterations) {\n      treatment <- c(rep(0, n / 2), rep(1, n / 2))\n      BDI <- 23 - 6 * treatment + rnorm(n, mean = 0, sd = sqrt(117))\n      df <- data.frame(treatment, BDI)\n      res <- lm(BDI ~ treatment, data = df)\n\n      # CHANGE: assign resulting p-value to specific slot in vector\n      p_values[i] <- summary(res)$coefficients[\"treatment\", \"Pr(>|t|)\"]\n    }\n\n    # Here we stil have a growing data.frame - but as this is only done 5 times, it does not matter.\n    result <- rbind(\n      result,\n      data.frame(n = n, power = sum(p_values < .005) / iterations)\n    )\n  }\n})\n\n# Combine the different timings in a data frame\ntimings <- rbind(t0[3], t1[3]) |> data.frame()\n\n# compute the absolute and relative difference of consecutive rows:\ntimings$diff <- c(\n  NA,\n  timings[2:nrow(timings), 1] - timings[1:(nrow(timings) - 1), 1]\n)\ntimings$rel_diff <- c(\n  NA,\n  timings[2:nrow(timings), \"diff\"] / timings[1:(nrow(timings) - 1), 1]\n) |>\n  round(3)\n\ntimings\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  elapsed   diff rel_diff\n1   7.140     NA       NA\n2   6.762 -0.378   -0.053\n```\n\n\n:::\n:::\n\n\nThis change gave a small speed-up of -0.378 seconds (or -5.3%).\n\n# Rule 2: Avoid data frames as far as possible\n\nUse matrizes instead of data frames wherever possible or avoid data frames altogether (as we do in the code below).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt2 <- system.time({\n  iterations <- 5000\n  ns <- seq(300, 500, by = 50)\n\n  result <- data.frame()\n\n  for (n in ns) {\n    treatment <- c(rep(0, n / 2), rep(1, n / 2))\n    p_values <- rep(NA, iterations)\n\n    for (i in 1:iterations) {\n      BDI <- 23 - 3 * treatment + rnorm(n, mean = 0, sd = sqrt(117))\n\n      # CHANGE: We don't need the data frame - just create the two variables\n      # in the environment and lm() takes them from there.\n      #df <- data.frame(treatment, BDI)\n      res <- lm(BDI ~ treatment)\n\n      p_values[i] <- summary(res)$coefficients[\"treatment\", \"Pr(>|t|)\"]\n    }\n\n    result <- rbind(\n      result,\n      data.frame(n = n, power = sum(p_values < .005) / iterations)\n    )\n  }\n})\n\ntimings <- rbind(t0[3], t1[3], t2[3]) |> data.frame()\ntimings$diff <- c(\n  NA,\n  timings[2:nrow(timings), 1] - timings[1:(nrow(timings) - 1), 1]\n)\ntimings$rel_diff <- c(\n  NA,\n  timings[2:nrow(timings), \"diff\"] / timings[1:(nrow(timings) - 1), 1]\n) |>\n  round(3)\ntimings\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  elapsed   diff rel_diff\n1   7.140     NA       NA\n2   6.762 -0.378   -0.053\n3   4.977 -1.785   -0.264\n```\n\n\n:::\n:::\n\n\nThis showed a substantial improvement of around -1.8 seconds; a relative gain of -26.4% (both compared to the preceding version).\n\n# Rule 3: Avoid unnecessary computations\n\nWhat do we actually need? In fact only the p-value for our focal predictor. But the `lm` function does so many more things, for example parsing the formula `BDI ~ treatment`.\n\nWe could strip away all overhead and do only the necessary steps: Fit the linear model, and retrieve the p-values (see [https://stackoverflow.com/q/49732933](https://stackoverflow.com/q/49732933)). This needs some deeper knowledge of the functions and some google-fu. When you do this, you should definitely compare your results with the original result from the `lm` function and verify that they are identical!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt3 <- system.time({\n  iterations <- 5000\n  ns <- seq(300, 500, by = 50)\n\n  result <- data.frame()\n\n  for (n in ns) {\n    # construct the design matrix: first column is all-1 (intercept), second column is the treatment factor\n    x <- cbind(\n      rep(1, n),\n      c(rep(0, n / 2), rep(1, n / 2))\n    )\n\n    p_values <- rep(NA, iterations)\n\n    for (i in 1:iterations) {\n      y <- 23 - 3 * x[, 2] + rnorm(n, mean = 0, sd = sqrt(117))\n\n      # For comparison - do we get the same results? Yes!\n      # res0 <- lm(y ~ x[, 2])\n      # summary(res0)\n\n      # fit the model:\n      m <- .lm.fit(x, y)\n\n      # compute p-values based on the residuals:\n      rss <- sum(m$residuals^2)\n      rdf <- length(y) - ncol(x)\n      resvar <- rss / rdf\n      R <- chol2inv(m$qr)\n      se <- sqrt(diag(R) * resvar)\n      ps <- 2 * pt(abs(m$coef / se), rdf, lower.tail = FALSE)\n\n      p_values[i] <- ps[2]\n    }\n\n    result <- rbind(\n      result,\n      data.frame(n = n, power = sum(p_values < .005) / iterations)\n    )\n  }\n})\ntimings <- rbind(t0[3], t1[3], t2[3], t3[3]) |> data.frame()\ntimings$diff <- c(\n  NA,\n  timings[2:nrow(timings), 1] - timings[1:(nrow(timings) - 1), 1]\n)\ntimings$rel_diff <- c(\n  NA,\n  timings[2:nrow(timings), \"diff\"] / timings[1:(nrow(timings) - 1), 1]\n) |>\n  round(3)\ntimings\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  elapsed   diff rel_diff\n1   7.140     NA       NA\n2   6.762 -0.378   -0.053\n3   4.977 -1.785   -0.264\n4   0.557 -4.420   -0.888\n```\n\n\n:::\n:::\n\nThis step led to a massive improvement of around -4.4 seconds; a relative gain of -88.8%.\n\n# Rule 4: Use optimized packages\n\nFor many statistical models, there are packages optimized for speed, see for example here:\n[https://stackoverflow.com/q/49732933](https://stackoverflow.com/q/49732933).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt4 <- system.time({\n  iterations <- 5000\n  ns <- seq(300, 500, by = 50)\n\n  result <- data.frame()\n\n  for (n in ns) {\n    # construct the design matrix: first column is all-1 (intercept), second column is the treatment factor\n    x <- cbind(\n      rep(1, n),\n      c(rep(0, n / 2), rep(1, n / 2))\n    )\n\n    p_values <- rep(NA, iterations)\n\n    for (i in 1:iterations) {\n      y <- 23 - 3 * x[, 2] + rnorm(n, mean = 0, sd = sqrt(117))\n\n      # For comparison - do we get the same results? Yes!\n      # res0 <- lm(y ~ x[, 2])\n      # summary(res0)\n\n      mdl <- RcppArmadillo::fastLmPure(x, y)\n\n      # compute the p-value - but only for the coefficient of interest!\n      p_values[i] <- 2 *\n        pt(\n          abs(mdl$coefficients[2] / mdl$stderr[2]),\n          mdl$df.residual,\n          lower.tail = FALSE\n        )\n    }\n\n    result <- rbind(\n      result,\n      data.frame(n = n, power = sum(p_values < .005) / iterations)\n    )\n  }\n})\ntimings <- rbind(t0[3], t1[3], t2[3], t3[3], t4[3]) |> data.frame()\ntimings$diff <- c(\n  NA,\n  timings[2:nrow(timings), 1] - timings[1:(nrow(timings) - 1), 1]\n)\ntimings$rel_diff <- c(\n  NA,\n  timings[2:nrow(timings), \"diff\"] / timings[1:(nrow(timings) - 1), 1]\n) |>\n  round(3)\ntimings\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  elapsed   diff rel_diff\n1   7.140     NA       NA\n2   6.762 -0.378   -0.053\n3   4.977 -1.785   -0.264\n4   0.557 -4.420   -0.888\n5   0.443 -0.114   -0.205\n```\n\n\n:::\n:::\n\n\nThis step made no visible increase in speed -- but as a bonus, it made our code much easier to read and shorter.\n\n\n# Rule 5: Go parallel\n\nBy default, R runs single-threaded. That means, a single CPU core works off all lines of code sequentially. When you optimized this single thread performance, the only way to gain more speed (except buying a faster computer) is to distribute the workload to multiple CPU cores that work in parallel. Every modern CPU comes with multiple cores (also called \"workers\" in the code); typically 4 to 8 on local computers and laptops. \n\n\n## Preparation: Wrap the simulation in a function\n\nThe first step does not really change a lot: We put the simulation code into a separate function that returns the quantity of interest (in our case: the focal p-value). Different settings of the simulation parameters, such as the sample size or the effect size, can be defined as parameters of the function. \n\nEvery single function call `sim()` now gives you one simulated p-value -- try it out!\n\nWe then use the `replicate` function to run the `sim` function many times and to store the resulting p-values in a vector. Programming the simulation in such a functional style also has the nice side effect that you do not have to pre-allocate the results vector; this is automatically done by the replicate function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Wrap the code for a single simulation into a function. It returns the quantity of interest.\nsim <- function(n = 100) {\n  # the \"n\" is now taken from the function parameter \"n\"\n  x <- cbind(\n    rep(1, n),\n    c(rep(0, n / 2), rep(1, n / 2))\n  )\n\n  y <- 23 - 3 * x[, 2] + rnorm(n, mean = 0, sd = sqrt(117))\n  mdl <- RcppArmadillo::fastLmPure(x, y)\n  p_val <- 2 *\n    pt(\n      abs(mdl$coefficients[2] / mdl$stderr[2]),\n      mdl$df.residual,\n      lower.tail = FALSE\n    )\n\n  return(p_val)\n}\n\nt5 <- system.time({\n  iterations <- 5000\n  ns <- seq(300, 500, by = 50)\n\n  result <- data.frame()\n\n  for (n in ns) {\n    p_values <- replicate(n = iterations, sim(n = n))\n    result <- rbind(\n      result,\n      data.frame(n = n, power = sum(p_values < .005) / iterations)\n    )\n  }\n})\ntimings <- rbind(t0[3], t1[3], t2[3], t3[3], t4[3], t5[3]) |> data.frame()\ntimings$diff <- c(\n  NA,\n  timings[2:nrow(timings), 1] - timings[1:(nrow(timings) - 1), 1]\n)\ntimings$rel_diff <- c(\n  NA,\n  timings[2:nrow(timings), \"diff\"] / timings[1:(nrow(timings) - 1), 1]\n) |>\n  round(3)\ntimings\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  elapsed   diff rel_diff\n1   7.140     NA       NA\n2   6.762 -0.378   -0.053\n3   4.977 -1.785   -0.264\n4   0.557 -4.420   -0.888\n5   0.443 -0.114   -0.205\n6   0.541  0.098    0.221\n```\n\n\n:::\n:::\n\nWhile this refactoring actually slightly increased computation time, we need this for the last, final optimization where we reap the benefits.\n\n## Run on multiple cores\n\nWith the use of the `replicate` function in the previous step, we prepared everything for an easy switch to multi-core processing. You only need to load the `future.apply` package, start a multi-core session with the `plan` command, and replace the `replicate` function call with `future_replicate`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show how many cores are available on your machine:\navailableCores()\n\n# with plan() you enter the parallel mode. Enter the number of workers (aka. CPU cores)\nplan(multisession, workers = 4)\n\nt6 <- system.time({\n  iterations <- 5000\n  ns <- seq(300, 500, by = 50)\n\n  result <- data.frame()\n\n  for (n in ns) {\n    # future.seed = TRUE is needed to set seeds in all parallel processes. Then the computation is reproducible.\n    p_values <- future_replicate(n = iterations, sim(n = n), future.seed = TRUE)\n    result <- rbind(\n      result,\n      data.frame(n = n, power = sum(p_values < .005) / iterations)\n    )\n  }\n})\n\ntimings <- rbind(t0[3], t1[3], t2[3], t3[3], t4[3], t5[3], t6[3]) |>\n  data.frame()\ntimings$diff <- c(\n  NA,\n  timings[2:nrow(timings), 1] - timings[1:(nrow(timings) - 1), 1]\n)\ntimings$rel_diff <- c(\n  NA,\n  timings[2:nrow(timings), \"diff\"] / timings[1:(nrow(timings) - 1), 1]\n) |>\n  round(3) |>\n  round(2)\ntimings\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n  elapsed   diff rel_diff\n1   7.140     NA       NA\n2   6.762 -0.378    -0.05\n3   4.977 -1.785    -0.26\n4   0.557 -4.420    -0.89\n5   0.443 -0.114    -0.20\n6   0.541  0.098     0.22\n7   0.465 -0.076    -0.14\n```\n\n\n:::\n:::\n\n\n\nThe speed improvement seems only small -- with 4 workers, one might expect that the computations only need 1/4th of the previous time. But parallel processing creates some overhead. For example, 4 separate R sessions need to be created and all packages, code (and sometimes data) need to be loaded in each session. Finally, all results must be collected and aggregated from all separate sessions. This can add up to substantial one-time costs. If your (single-core) computations only take a few seconds or less, parallel processing can even take *longer*. \n\n\n# The final speed test: Burn your machine 🔥\n\nLet's see if parallel processing has an advantage when we have longer computations. We now expand the simulation by exploring a broad parameter range (n ranging from 100 to 1000) and increasing the iterations to 20,000 for more stable results. (See also: \"[Bonus: How many Monte Carlo iterations are necessary?](how-many-iterations.qmd)\")\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplan(multisession, workers = 4)\n\niterations <- 20000\nns <- seq(100, 1000, by = 50)\nresult_single <- result_parallel <- data.frame()\n\n# single core\nt_single <- system.time({\n  for (n in ns) {\n    p_values <- replicate(n = iterations, sim(n = n))\n    result_single <- rbind(\n      result_single,\n      data.frame(n = n, power = sum(p_values < .005) / iterations)\n    )\n  }\n})\n\n# multi-core\nt_parallel <- system.time({\n  for (n in ns) {\n    p_values <- future_replicate(n = iterations, sim(n = n), future.seed = TRUE)\n    result_parallel <- rbind(\n      result_parallel,\n      data.frame(n = n, power = sum(p_values < .005) / iterations)\n    )\n  }\n})\n\n# compare results\ncbind(result_single, power.parallel = result_parallel[, 2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      n   power power.parallel\n1   100 0.07070        0.07360\n2   150 0.12895        0.12865\n3   200 0.19230        0.19600\n4   250 0.26080        0.26130\n5   300 0.33195        0.34250\n6   350 0.40875        0.41300\n7   400 0.47985        0.47600\n8   450 0.55080        0.55150\n9   500 0.61105        0.61605\n10  550 0.67180        0.66535\n11  600 0.71560        0.71845\n12  650 0.76000        0.75880\n13  700 0.80195        0.80335\n14  750 0.83355        0.83695\n15  800 0.86645        0.86615\n16  850 0.89120        0.88820\n17  900 0.91095        0.91310\n18  950 0.92460        0.92995\n19 1000 0.94485        0.94185\n```\n\n\n:::\n\n```{.r .cell-code}\nrbind(t_single, t_parallel) |> data.frame()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           user.self sys.self elapsed user.child sys.child\nt_single      10.063    0.107  10.243          0         0\nt_parallel     1.017    0.038   4.100          0         0\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\nWith this optimized setup, we are running 380000 simulations in just 4.1 seconds. If you try this with the first code version, it takes 110.366 seconds.\n\n**With the final, parallelized version we have a 26.9x speed gain relative to the first version!**\n\n\n# Recap\n\nWe covered the most important steps for speeding up your code in R:\n\n1. No growing vectors/data frames. Solution: Pre-allocate the results vector.\n2. Avoid data frames. Solution: Use matrices wherever possible, or switch to data.table for more complex data structures (not covered here).\n3. Avoid unnecessary computations and/or switch to optimized packages that do the same computations much faster, such as the package `Rfast`.\n4. Switch to parallel processing. Solution: If you already programmed your simulations with the `replicate` function, it is very easy with the `future.apply` package.\n\nSome steps, such as avoiding growing vectors, didn't help much in our current example, but will help a lot in other scenarios.\n\nThere are *many* blog post showing and comparing strategies to increase R performance, e.g.:\n\n-   [https://www.r-bloggers.com/2016/01/strategies-to-speedup-r-code/](https://www.r-bloggers.com/2016/01/strategies-to-speedup-r-code/)\n-   [https://adv-r.hadley.nz/perf-improve.html](https://adv-r.hadley.nz/perf-improve.html)\n-   [https://csgillespie.github.io/efficientR/performance.html](https://csgillespie.github.io/efficientR/performance.html)\n\n::: callout-note\n# But always remember:\n\n\"We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil.\nYet we should not pass up our opportunities in that critical 3%.\"\n\nDonald Knuth *(Structured Programming with go to Statements, ACM Journal Computing Surveys, Vol 6, No. 4, Dec. 1974. p. 268)*\n:::\n\n# Session Info\n\nThese speed measurements have been performed on a 2025 MacBook Pro with M4 processor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.1 (2026-06-24)\nPlatform: aarch64-apple-darwin23\nRunning under: macOS Tahoe 26.5.1\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRblas.0.dylib \nLAPACK: /Library/Frameworks/R.framework/Versions/4.6/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\ntime zone: Europe/Berlin\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices datasets  utils     methods   base     \n\nother attached packages:\n[1] future.apply_1.20.2    future_1.75.0          RcppArmadillo_15.4.2-1\n\nloaded via a namespace (and not attached):\n [1] digest_0.6.39     codetools_0.2-20  fastmap_1.2.0     xfun_0.60        \n [5] knitr_1.51        parallel_4.6.1    htmltools_0.5.9   rmarkdown_2.31   \n [9] cli_3.6.6         parallelly_1.48.0 renv_1.2.4        compiler_4.6.1   \n[13] globals_0.19.1    tools_4.6.1       listenv_1.0.0     evaluate_1.0.5   \n[17] Rcpp_1.1.2        yaml_2.3.12       rlang_1.3.0       jsonlite_2.0.0   \n```\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}