{
  "hash": "ae2158140d1df72ddebe21382f9bc059",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Ch. 4: Linear Mixed Models / Multilevel models\"\nauthor: \"Felix Schönbrodt\"\n---\n\n*Reading/working time: ~60 min.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Preparation: Install and load all necessary packages\n# install.packages(c(\"lme4\", \"lmerTest\", \"ggplot2\", \"tidyr\", \"Rfast\", \"future.apply\"))\n\nlibrary(lme4) # for estimating LMMs\nlibrary(lmerTest) # to get p-values for lme4\nlibrary(ggplot2) # for plotting\nlibrary(tidyr) # for reshaping data from wide to long\nlibrary(Rfast) # fast creation of correlated variables\nlibrary(future.apply) # for parallel processing\n\n# plan() initializes parallel processing,\n# for faster code execution\n# By default, it uses all available cores\nplan(multisession)\n```\n:::\n\n\nIn order to keep this chapter at a reasonable length, we focus on how to simulate the mixed effects/multi-level model and spend less time discussing how to arrive at plausible parameter values. Please read Chapters [1](lm1.qmd) and [2](lm2.qmd) for multiple examples where the parameter values are derived from (a) the literature (e.g., bias-corrected meta-analyses), (b) pilot data, or (c) plausibility constraints.\n\nFurthermore, we'll use the techniques described in the Chapter [\"Bonus: Optimizing R code for speed\"](optimizing-code.qmd), otherwise the simulations are too slow. If you wonder about the unknown commands in the code, please read the bonus chapter to learn how to considerably speed up your code!\n\nWe continue to work with the \"Beat the blues\" (`BtheB`) data set from the `HSAUR` R package. As there are multiple post-treatment measurements (after 2, 3, 6, and 8 months) we can create a nice longitudinal multilevel data set, with measurement points on level 1 (L1) and persons on level 2 (L2). We will work with the `lme4` package to run the mixed-effect models.\n\nFor that, we first have to transform the pilot data set into the long format:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the data\ndata(\"BtheB\", package = \"HSAUR\")\nBtheB$person_id <- 1:nrow(BtheB)\n\nBtheB_long <- pivot_longer(\n  BtheB,\n  cols = matches(\"^bdi\\\\.\\\\d\"),\n  values_to = \"BDI\",\n  names_to = \"variable\"\n)\nBtheB_long$time <- substr(BtheB_long$variable, 5, 5) |> as.integer()\n```\n:::\n\n\nHere we plot the trajectory of the first 20 participants. As you can see, there are missing values; not all participants have all follow-up values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  BtheB_long[BtheB_long$person_id <= 20, ],\n  aes(x = time, y = BDI, group = person_id)\n) +\n  geom_point() +\n  geom_line() +\n  facet_wrap(~person_id)\n```\n\n::: {.cell-output-display}\n![](lmm_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n# A random-intercept, fixed-slope model\n\nWe start with a simple model and analyze the trajectory of the BDI score across time (we ignore the treatment factor for the moment). Hence, the question for this model is: Is there a linear trend over time in BDI scores?\n\n## The formulas\n\n* i = index for time points\n* j = index for persons\n\nLevel 1 equation:\n$$\n\\text{BDI}_{ij} = \\beta_{0j} + \\beta_{1j} time_{ij} + e_{ij}\n$$\nLevel 2 equations:\n$$\n\\beta_{0j} = \\gamma_{00} + u_{0j}\\\\\n\\beta_{1j} = \\gamma_{10}\n$$\nCombined equation:\n$$\n\\text{BDI}_{ij} = \\gamma_{00} + \\gamma_{10} time_{ij}  + u_{0j} + e_{ij} \\\\\n\\\\\ne_{ij} \\mathop{\\sim}\\limits^{\\mathrm{iid}} N(mean=0, var=\\sigma^2) \\\\\nu_{0j} \\mathop{\\sim}\\limits^{\\mathrm{iid}} N(mean=0, var=\\tau_{00})\n$$\n\n## Analysis in pilot data\nFirst, let's run the analysis model in the pilot data. To make the intercept more interpretable, we center it on the first post-measurement by subtracting 2 (i.e., month \"2\" becomes month \"0\" etc.).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBtheB_long$time.c <- BtheB_long$time - 2\n\nl0 <- lmer(BDI ~ 1 + time.c + (1 | person_id), data = BtheB_long)\nsummary(l0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: BDI ~ 1 + time.c + (1 | person_id)\n   Data: BtheB_long\n\nREML criterion at convergence: 1929.4\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-2.6308 -0.4698 -0.0810  0.3536  3.7142 \n\nRandom effects:\n Groups    Name        Variance Std.Dev.\n person_id (Intercept) 97.15    9.857   \n Residual              25.48    5.048   \nNumber of obs: 280, groups:  person_id, 97\n\nFixed effects:\n            Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)  16.9691     1.0990 110.4143  15.441  < 2e-16 ***\ntime.c       -0.6869     0.1486 192.8764  -4.623 6.91e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n       (Intr)\ntime.c -0.267\n```\n\n\n:::\n\n```{.r .cell-code}\n# Compute ICC\n97.15 / (97.15 + 25.48)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7922205\n```\n\n\n:::\n:::\n\n\nHence, in the pilot data there is a significant negative trend -- with each month, participants have a decrease of 0.7 BDI points. But remember that in this data set *all* of the participants have been treated (with one of two treatments). For a passive control group we probably would expect no, or at least a much smaller negative trend over time. (There could be spontaneous remissions, but if this effect is assumed to be very strong, there would be no need for psychotherapy). The ICC is around 79%, hence a huge amount of random variance can be attributed to differences between persons.\n\nThe grand intercept $\\gamma_{00}$ is 17. This is also the average post-treatment value that we assumed in our previous models in Chapters 1 and 2.\n\nFor the random intercept variance and the residual variance, we take generously rounded estimates from the pilot data: $\\tau_{00} = 100$ and $\\sigma^2 = 25$.\n\n::: {.callout-tip}\n# Default values for ICCs?\nSometimes the random intercept variance is parametrized via the ICC. Some publications discuss \"typical\" ICCs (see also Scherbaum & Ferreter, 2008):\n\n- „ICC values typically range between .05 and .20“ (Snijders & Bosker, 1999; Bliese, 2000) \n- „values greater than .30 will be rare“ (Bliese, 2000)\n- „median value of .12; this is likely an overestimate“ (James, 1982)\n- „a value between .10 and .15 will provide a conservative estimate of the ICC when it cannot be precisely computed“\n\nBut there are some research fields where ICCs > 30% are not uncommon -- as you can see in our own pilot data, where the ICC was 79%! Again, defaults based on \"typical values in the literature\" might be better than blind guessing, but nothing beats domain knowledge.\n:::\n\n## Let's simulate\n\nThe next script shows how to simulate multilevel data with a random intercept. We first create an L2 data set (where each row is once participant). This contains a person id (which is necessary to merge the L1 and the L2 data set) and the random intercepts (i.e., the random deviations of persons from the fixed intercept). In more complex models, this also contains all L2 predictors.\n\nNext we create an L1 data set and then merge both into one long format data set.\nWe closely simulate the situation of the pilot data: All participants are treated and show a negative trend.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#------  Setting the model parameters ---------------\n# between-person random intercept variance: var(u_0j) = tau_00\ntau_00 <- 100\n\ngamma_00 <- 17 # the grand (fixed) intercept\ngamma_10 <- -0.7 # the fixed slope for time\nresidual_var <- 25\n\nn_persons <- 100\n\n# Create an L2 (person-level) data set; each row is one person\ndf_L2 <- data.frame(\n  person_id = 1:n_persons,\n  u_0j = rnorm(n_persons, mean = 0, sd = sqrt(tau_00))\n)\n\n# Create an L1 (measurement-point-level) data set; each row is one measurement\ndf_L1 <- data.frame(\n  person_id = rep(1:n_persons, each = 4), # create 4 rows for each person (as we have 4 measurements)\n  time.c = rep(c(0, 2, 4, 6), times = n_persons)\n)\n\n# combine to a long format data set\ndf_long <- merge(df_L1, df_L2, by = \"person_id\")\n\n# compute the DV by writing down the combined equation\ndf_long <- within(df_long, {\n  BDI <- gamma_00 +\n    gamma_10 * time.c +\n    u_0j +\n    rnorm(n_persons * 4, mean = 0, sd = sqrt(residual_var))\n})\n\nl1 <- lmer(BDI ~ 1 + time.c + (1 | person_id), data = df_long)\nsummary(l1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: BDI ~ 1 + time.c + (1 | person_id)\n   Data: df_long\n\nREML criterion at convergence: 2695\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-3.3313 -0.5559  0.0243  0.6234  2.5509 \n\nRandom effects:\n Groups    Name        Variance Std.Dev.\n person_id (Intercept) 89.26    9.448   \n Residual              25.07    5.007   \nNumber of obs: 400, groups:  person_id, 100\n\nFixed effects:\n            Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)  17.9385     1.0335 123.1978  17.357  < 2e-16 ***\ntime.c       -0.6766     0.1120 299.0000  -6.043  4.5e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n       (Intr)\ntime.c -0.325\n```\n\n\n:::\n:::\n\n\nNow we put this data generating script into a function and run our power analysis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note: This code could be more optimized for speed, but this way is easier to understand\nsim4 <- function(\n  n_persons = 100,\n  tau_00 = 100,\n  gamma_00 = 17,\n  gamma_10 = -0.7,\n  residual_var = 25,\n  print = FALSE\n) {\n  df_L2 <- data.frame(\n    person_id = 1:n_persons,\n    u_0j = rnorm(n_persons, mean = 0, sd = sqrt(tau_00))\n  )\n\n  df_L1 <- data.frame(\n    person_id = rep(1:n_persons, each = 4), # create 4 rows for each person (as we have 4 measurements)\n    time.c = rep(c(0, 2, 4, 6), times = n_persons)\n  )\n\n  # combine to a long format data set\n  df_long <- merge(df_L1, df_L2, by = \"person_id\")\n\n  # simulate response variable, based on combined equation\n  df_long <- within(df_long, {\n    BDI <- gamma_00 +\n      gamma_10 * time.c +\n      u_0j +\n      rnorm(n_persons * 4, mean = 0, sd = sqrt(residual_var))\n  })\n\n  # compute p-values\n  # these options might speed up code execution a little bit:\n  # , control=lmerControl(optimizer=\"bobyqa\", calc.derivs = FALSE)\n  l1 <- lmer(BDI ~ 1 + time.c + (1 | person_id), data = df_long)\n\n  if (print == TRUE) {\n    print(summary(l1))\n  } else {\n    return(summary(l1)$coefficients[, \"Pr(>|t|)\"])\n  }\n}\n\n\nset.seed(0xBEEF)\niterations <- 1000\nns <- seq(30, 50, by = 5)\n\nresult <- data.frame()\n\nfor (n_persons in ns) {\n  system.time({\n    p_values <- future_replicate(\n      iterations,\n      sim4(n_persons = n_persons),\n      future.seed = TRUE\n    )\n  })\n\n  result <- rbind(\n    result,\n    data.frame(\n      n = n_persons,\n      power_intercept = sum(p_values[1, ] < .005) / iterations,\n      power_time.c = sum(p_values[2, ] < .005) / iterations\n    )\n  )\n\n  # show the result after each run (not shown here in the tutorial)\n  print(result)\n}\n```\n:::\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n   n power_intercept power_time.c\n1 30               1        0.700\n2 35               1        0.786\n3 40               1        0.874\n4 45               1        0.912\n5 50               1        0.937\n```\n\n\n:::\n:::\n\n\nHence, we need around 36 persons to achieve a power of 80% to detect this slope.\n\n## Comparison with other approaches\n\nMurayama and colleagues (2022) recently released an approximate but easy approach for LMM power analysis based on pilot data.\nThey also provide an interactive [Shiny app](https://koumurayama.shinyapps.io/summary_statistics_based_power/).\n\nGo to the tab \"Level-1 predictor -> Planning L2 sample size only\" and enter the values from the pilot study into the fields in the left panel:\n\n* (Absolute) t value of the focal level-1 predictor = 4.623\n* Level-2 sample size = 97\n* Number of cross-level interactions related to the focal level-1 predictor = 0\n\nThis approximation yields very close values to our simulation:\n\n![Screenshot from Murayama app](images/lmm-murayama-app-example.png)\n\nAnother option is the app \"[PowerAnalysisIL](https://github.com/ginettelafit/PowerAnalysisIL)\" by Lafit (2021). In that app you would need to choose \"Model 4: Effect of a level-1 continuous predictor (fixed slope)\" and set \"Autocorrelation of level-1 errors\" to zero to estimate an equivalent model to ours. This app, however, is much slower than our own simulations and cannot perfectly mirror our model, as the continuous L1 predictor cannot be defined exactly as we need it.\n\nNonetheless, the estimates are not far away from ours:\n\n![Screenshot from Lafit app](images/lmm-lafit-example.png)\n\n\n# A random-intercept, random-slope model with cross-level interaction\n\nWe now make the model more complex by (a) adding an L2 predictor (treatment vs. control), (b) allowing random slopes for the time effect, and (c) model a cross-level interaction (i.e., does the slope differ between treatment and control group?).\n\nThe main effect for `treatment` reveals group differences when the other predictor, `time`, is zero (i.e., at the first post-treatment measurement). The main effect for `time` now is a *conditional* effect, as it models the time trend for the control group (i.e., when `treatment` is zero).\n\n## The formulas\n\n* i = index for time points\n* j = index for persons\n\nLevel 1 equation:\n$$\n\\text{BDI}_{ij} = \\beta_{0j} + \\beta_{1j} time_{ij} + e_{ij}\n$$\nLevel 2 equations:\n$$\n\\beta_{0j} = \\gamma_{00} + \\gamma_{01} \\text{treatment}_j + u_{0j}\\\\\n\\beta_{1j} = \\gamma_{10} + \\gamma_{11} \\text{treatment}_j + u_{1j}\n$$\nCombined equation:\n$$\n\\text{BDI}_{ij} = \\gamma_{00} + \\gamma_{01} \\text{treatment}_j + \\gamma_{10} time_{ij} +  \\gamma_{11} \\text{treatment}_j time_{ij} + u_{1j} time_{ij} + u_{0j} + e_{ij} \\\\\n\\\\\ne_{ij} \\mathop{\\sim}\\limits^{\\mathrm{iid}} N(mean=0, var=\\sigma^2) \\\\\nu_{0j} \\mathop{\\sim}\\limits^{\\mathrm{iid}} N(mean=0, var=\\tau_{00}) \\\\\nu_{1j} \\mathop{\\sim}\\limits^{\\mathrm{iid}} N(mean=0, var=\\tau_{11}) \\\\\ncov(u_{0j}, u_{1j}) = \\tau_{01}\n$$\n\n## Setting the population parameter values\n\nWe need to assume four additional population values, namely: $\\tau_{11}$ (the variance of random slopes), $\\tau_{01}$ (the intercept-slope-covariance), $\\gamma_{01}$ (the treatment main effect), and $\\gamma_{11}$ (the interaction effect).\n\n*Fixed effects:* \n\n* The grand intercept $\\gamma_{00}$ now is set to 23.\n* The treatment effect $\\gamma_{01}$ is set to -6 (as before). In this more complex model, the treatment effect refers to a difference between treatment and control group directly after treatment. \n* As mentioned above, it is reasonable to assume that there should be no marked trend in a passive control group. Therefore, we set the conditional main effect for time, $\\gamma_{10}$ to 0. \n* For the interaction effect, we expect a steeper decline in the treatment group (e.g., because the treatment \"unfolds\" its effect over time). If we set the interaction effect to -0.7, this translates to a predicted slope of -0.7 in the treatment group: $\\gamma_{10} time_{ij} +  \\gamma_{11} \\text{treatment}_j time_{ij} =  (\\gamma_{10} +  \\gamma_{11} \\text{treatment}_j) time_{ij}$. \n\nIs this slope of -0.7, estimated from the pilot data, reasonable?\nLet's extrapolate the trend: Treated patients have an average BDI score of 17 (directly after treatment). If they decline 0.7 points per month, they would have a BDI difference of $12*-0.7 = -8.4$ after one year and are at around 9 BDI points. With that decline, they would have moved from a mild depression to a minimal depression. This seems plausible.\n\n*Random terms:* \n\n* Assume that ~95% of slopes in the treatment group lie between -0.7 ± 0.3 (i.e., between -0.4 and -1). This corresponds to a standard deviation of 0.15 and consequently a variance of $\\tau_{11} = 0.15^2 = 0.0225$. \n* We assume no random effect correlation, so $\\tau_{01} = 0$. \n\nAs recommended in the last chapter, we visualize this assumed interaction effect by a hand drawing:\n\n![hand-drawn interaction plot](images/bdi-interaction-2.jpg)\n\nLooks good!\n\n\n## Let's simulate\n\n\n::: {.cell warnings='false'}\n\n```{.r .cell-code}\nsim5 <- function(\n  n_persons = 100,\n  tau_00 = 100,\n  tau_11 = 0.0225,\n  tau_01 = 0,\n  gamma_00 = 23,\n  gamma_01 = -6,\n  gamma_10 = 0,\n  gamma_11 = -0.7,\n  residual_var = 25,\n  print = FALSE\n) {\n  # create (correlated) random effect structure\n  mu <- c(0, 0)\n  sigma <- matrix(\n    c(tau_00, tau_01, tau_01, tau_11),\n    nrow = 2,\n    byrow = TRUE\n  )\n  RE <- rmvnorm(n = n_persons, mu = mu, sigma = sigma) |> data.frame()\n  names(RE) <- c(\"u_0j\", \"u_1j\")\n\n  df_L1 <- data.frame(\n    person_id = 1:n_persons,\n    u_0j = RE$u_0j,\n    u_1j = RE$u_1j,\n    treatment = rep(c(0, 1), times = n_persons / 2)\n  )\n\n  df_L2 <- data.frame(\n    person_id = rep(1:n_persons, each = 4), # create 4 rows for each person (as we have 4 measurements)\n    time.c = rep(c(0, 2, 4, 6), times = n_persons)\n  )\n\n  # combine to a long format data set\n  df_long <- merge(df_L1, df_L2, by = \"person_id\")\n\n  # simulate response variable, based on combined equation\n  df_long <- within(df_long, {\n    BDI <- gamma_00 + # intercept\n      gamma_10 * time.c +\n      gamma_01 * treatment +\n      gamma_11 * time.c * treatment + # fixed terms\n      u_0j +\n      u_1j * time.c +\n      rnorm(n_persons * 4, mean = 0, sd = sqrt(residual_var)) # random terms\n  })\n\n  # for debugging: plot some simulated participants\n  #ggplot(df_long[df_long$person_id <=20, ], aes(x=time.c, y=BDI, color=factor(treatment), group=person_id)) +\n  # geom_point() + geom_line() + facet_wrap(~person_id)\n\n  # ggplot(df_long, aes(x=time.c, y=BDI, color=factor(treatment))) +\n  # stat_summary(fun.data=mean_cl_normal, geom = \"pointrange\")\n\n  # compute p-values\n  # these options might speed up code execution a little bit:\n  # , control=lmerControl(optimizer=\"bobyqa\", calc.derivs = FALSE)\n  l1 <- lmer(\n    BDI ~ 1 + time.c * treatment + (1 + time.c | person_id),\n    data = df_long\n  )\n\n  if (print == TRUE) {\n    print(summary(l1))\n  } else {\n    return(summary(l1)$coefficients[, \"Pr(>|t|)\"])\n  }\n}\n\n\nset.seed(0xBEEF)\niterations <- 1000\nns <- seq(60, 200, by = 10) # must be dividable by 2\n\nresult <- data.frame()\n\nfor (n_persons in ns) {\n  system.time({\n    p_values <- future_replicate(\n      iterations,\n      sim5(n_persons = n_persons),\n      future.seed = TRUE\n    )\n  })\n\n  result <- rbind(\n    result,\n    data.frame(\n      n = n_persons,\n      power_intercept = sum(p_values[1, ] < .005) / iterations,\n      power_time.c = sum(p_values[2, ] < .005) / iterations,\n      power_treatment = sum(p_values[3, ] < .005) / iterations,\n      power_IA = sum(p_values[4, ] < .005) / iterations\n    )\n  )\n\n  # show the result after each run (not shown here in the tutorial)\n  print(result)\n}\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n     n power_intercept power_time.c power_treatment power_IA\n1   60               1        0.004           0.218    0.316\n2   70               1        0.007           0.276    0.409\n3   80               1        0.004           0.367    0.453\n4   90               1        0.005           0.415    0.504\n5  100               1        0.002           0.488    0.563\n6  110               1        0.006           0.502    0.615\n7  120               1        0.007           0.551    0.697\n8  130               1        0.004           0.634    0.766\n9  140               1        0.005           0.681    0.787\n10 150               1        0.004           0.722    0.844\n11 160               1        0.007           0.729    0.837\n12 170               1        0.003           0.779    0.857\n13 180               1        0.005           0.804    0.884\n14 190               1        0.002           0.835    0.914\n15 200               1        0.005           0.865    0.938\n```\n\n\n:::\n:::\n\n\nYou will see a lot of warnings about `boundary (singular) fit` -- you can generally ignore these; they typically occur when one of the random variances is exactly zero; but the fixed effect estimates (which are our focus here) are still valid. You will also see some rare warnings about `Model failed to converge with max|grad|`. In this case, the optimizer did not converge with the required precision, but typically still is very close. Finally, there are some warnings `Model failed to converge with 1 negative eigenvalue`. These instances give wrong results. However, if in our thousands of simulations some very few models did not converge, this makes no noticeable difference. If, however, the majority of your models does not converge this is a hint that your simulation has some errors.\n\nConcerning the computed power, we see that we need around 180 participants for the treatment main effect (which mirrors the result from Chapter 1) and around 140 participants for detecting the interaction effect. As there is no main effect for `time.c` (it has been simulated as zero), the power stays always around the $\\alpha$-level.\n\n# Ways forward\n\nWhile this power analysis could be approximated with existing apps, there are many useful extensions of the simulations that will not be possible in existing apps. Here are some examples:\n\n- We know from the pilot data that there is a lot of **participant drop-out**. We could easily simulate that drop-out (e.g., missing completely at random, MCAR) by setting, say, 10% of all BDI values to `NA` from $t_2$ on, additional 10% from $t_3$ on, etc.\n- We could simulate **floor effects**: Currently, the simulated BDI scores can drop below zero. A more realistic data generating model would cap these values at zero. This restricts the range, diminishes the mean difference and therefore lowers the power.\n- So far, the tutorial only covered a priori power analysis, where the sample size is the target. With an existing data set, you could do, for example, a **sensitivity power analysis** by varying the effect size in the outer loop (and keeping sample size constant).\n\n# Other packages\n\nThe `faux` package offers an elegant interface to [simulate multilevel data](https://debruine.github.io/faux/articles/sim_mixed.html#building-multilevel-designs):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"devtools\")\n# devtools::install_github(\"debruine/faux\")\nlibrary(faux)\n\nsim_faux <- function(n_persons = 100, print = FALSE) {\n  df <- add_random(person_id = n_persons) %>%\n    add_within(\"person_id\", time.c = 0:3) %>%\n    add_between(\"person_id\", group = c(\"treatment\", \"control\")) %>%\n    add_recode(\"group\", \"condition\", control = 0, treatment = 1) %>%\n    add_ranef(\"person_id\", u0j = sqrt(100)) %>%\n    add_ranef(sigma = sqrt(25))\n\n  df$time.c <- as.integer(as.character(df$time.c)) * 2\n\n  # compute DV\n  df$BDI <- 17 - 0.7 * df$time.c + df$u0j + df$sigma\n\n  l1 <- lmer(BDI ~ 1 + time.c + (1 | person_id), data = df)\n\n  if (print == TRUE) {\n    print(summary(l1))\n  } else {\n    return(summary(l1)$coefficients[, \"Pr(>|t|)\"])\n  }\n}\n```\n:::\n\n\nWhen you plug this simulation function into our power analysis loop, you will get the same results.\n\n## References\n\nScherbaum, C. A., & Ferreter, J. M. (2008). Estimating Statistical Power and Required Sample Sizes for Organizational Research Using Multilevel Modeling. Organizational Research Methods, 12(2), 347–367. http://doi.org/10.1177/1094428107308906\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}