{
  "hash": "511d92132c4d6df2f7683ac2c5e94a8b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Ch. 5: Structural Equation Models\"\nauthor: Moritz Fischer\n---\n\n*Reading/working time: ~50 min.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(c(\"lavaan\", \"ggplot2\", \"Rfast\", \"MBESS\", \"future.apply\"), dependencies = TRUE)\n\nlibrary(\"lavaan\")\nlibrary(\"Rfast\")\nlibrary(\"ggplot2\")\nlibrary(\"dplyr\")\nlibrary(\"MBESS\")\nlibrary(future.apply)\n# this initializes parallel processing, for faster code execution\n# By default, it uses all available cores\nplan(multisession)\n```\n:::\n\n\nIn this chapter, we will focus on some rather simple Structural Equation Models (SEM). The goal is to illustrate how simulations can be used to estimate statistical power to detect a given effect in a SEM. In the context of SEMs, the focal effect may be for instance a fit index (e.g., Chi-Square, Root Mean Square Error of Approximation, etc.) or a model coefficient (e.g., a regression coefficient for the association between two latent factors). In this chapter, we only focus on the latter, that is power analyses for regression coefficients in the context of SEM. Please see the bonus chapter titled \"[Power analysis for fit indices in SEM](sem-fit-index.qmd)\" if you're interested in power analyses for fit indices.\n\n::: {.callout-note}\nIn this chapter, we'll use the parallelization techniques described in the Chapter [\"Bonus: Optimizing R code for speed\"](optimizing-code.qmd), otherwise the simulations are too slow. If you wonder about the unknown commands in the code, please read the bonus chapter to learn how to considerably speed up your code! But nonetheless, running some of the chunks in this chapter will require quite some time. We therefore decided to use 500 iterations per simulation only in this chapter; please keep in mind that you should use more iterations in order to obtain more precise estimates! \n:::\n\n# A simulation-based power analysis for a single regression coefficient between latent variables\n\nLet's consider the following example: We are planning to conduct a study investigating whether people's openness to experience (as conceptualized in the big five personality traits) relates negatively to generalized prejudice, that is a latent variable comprising prejudice towards different social groups (e.g., women, foreigners, homosexuals, disabled people). We could plan to scrutinize this prediction with a SEM in which both openness to experience and generalized prejudice are modeled as latent variables. \n\n::: {.callout-note}\n\nPlease note that the predictions used as examples in this chapter are not necessarily theoretically meaningful hypotheses, we merely use them to illustrate the mechanics of simulation-based power analyses in the context of SEM.\n\n:::\n\n\n## Let's get some real data as starting point\n\nJust like for any other simulation-based power analysis, we first need to come up with plausible estimates of the distribution of the (manifest) variables. For the sake of simplicity, let's assume that there is a published study that measured manifestations of our two latent variables and that the corresponding data set is publicly available. For the purpose of this tutorial, we will draw on a publication by Bergh et al. ([2016](https://www.researchgate.net/publication/306939541_Is_group_membership_necessary_for_understanding_generalized_prejudice_A_re-evaluation_of_why_prejudices_are_interrelated)) and the corresponding data set which has been made accessible as part of the `MPsychoR` package. Let's take a look at this data set.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"MPsychoR\")\nlibrary(MPsychoR)\n\ndata(\"Bergh\")\nattach(Bergh)\n\n#let's take a look\nhead(Bergh)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        EP    SP  HP       DP     A1       A2       A3     O1       O2       O3\n1 2.666667 3.125 1.4 2.818182 3.4375 3.600000 3.352941 2.8750 3.400000 3.176471\n2 2.666667 3.250 1.4 2.545455 2.3125 2.666667 3.117647 4.4375 3.866667 4.470588\n3 1.000000 1.625 2.7 2.000000 3.5625 4.600000 3.941176 4.2500 3.666667 3.705882\n4 2.666667 2.750 1.8 2.818182 2.7500 3.200000 3.352941 2.8750 3.400000 3.117647\n5 2.888889 3.250 2.7 3.000000 3.2500 4.200000 3.764706 3.9375 4.400000 4.294118\n6 2.000000 2.375 1.7 2.181818 3.2500 3.333333 2.941176 3.8125 3.066667 3.411765\n  gender\n1   male\n2   male\n3   male\n4   male\n5   male\n6   male\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(Bergh)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          EP    SP  HP       DP     A1       A2       A3     O1       O2\n856 2.000000 2.500 1.0 2.363636 3.3125 3.800000 3.705882 3.6875 3.733333\n857 1.555556 1.875 1.1 1.818182 2.6250 3.733333 3.000000 3.3125 2.800000\n858 3.000000 2.750 1.0 1.909091 3.3125 3.533333 3.882353 4.0000 3.533333\n859 1.444444 1.250 1.0 1.000000 3.8750 3.800000 3.529412 3.9375 3.533333\n860 1.222222 1.625 1.0 2.363636 2.8750 3.600000 3.411765 2.8125 3.600000\n861 1.555556 1.750 1.0 1.090909 3.3750 4.266667 4.058824 3.3750 2.800000\n          O3 gender\n856 4.411765 female\n857 3.529412 female\n858 3.823529 female\n859 3.411765 female\n860 3.058824 female\n861 3.588235 female\n```\n\n\n:::\n:::\n\n\nThis data set comprises 11 variables measured in 861 participants. For now, we will focus on the following measured variables: \n\n-   `EP` is a continuous variable measuring ethnic prejudice. \n-   `SP` is a continuous variable measuring sexism. \n-   `HP` is a continuous variable measuring sexual prejudice towards gays and lesbians. \n-   `DP` is a continuous variable measuring prejudice toward people with disabilities. \n-   `O1`, `O2`, and `O3` are three items measuring openness to experience.\n\nTo get an impression of this data, we look at the correlations of the variables we're interested in.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(cbind(EP, SP, HP, DP, O1, O2, O3)) |> round(2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      EP    SP    HP    DP    O1    O2    O3\nEP  1.00  0.53  0.25  0.53 -0.35 -0.36 -0.41\nSP  0.53  1.00  0.22  0.53 -0.33 -0.31 -0.33\nHP  0.25  0.22  1.00  0.24 -0.23 -0.30 -0.29\nDP  0.53  0.53  0.24  1.00 -0.30 -0.33 -0.34\nO1 -0.35 -0.33 -0.23 -0.30  1.00  0.66  0.74\nO2 -0.36 -0.31 -0.30 -0.33  0.66  1.00  0.71\nO3 -0.41 -0.33 -0.29 -0.34  0.74  0.71  1.00\n```\n\n\n:::\n:::\n\n\nAs we have discussed in the previous chapters, the starting point of every simulation-based power analysis is to specify the population parameters of the variables of interest. In our example, we can estimate the population parameters from the study by Bergh et al. (2016). We start by calculating the means of the  variables, rounding them generously, and storing them in a vector called `means_vector`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#store means\nmeans_vector <- c(\n  mean(EP),\n  mean(SP),\n  mean(HP),\n  mean(DP),\n  mean(O1),\n  mean(O2),\n  mean(O3)\n) |>\n  round(2)\n\n#Let's take a look\nmeans_vector\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.99 2.11 1.22 2.06 3.55 3.49 3.61\n```\n\n\n:::\n:::\n\n\nWe also need the variance-covariance matrix of our variables in order to simulate data. Luckily, we can estimate this from the Bergh et al. data as well. There are two ways to do this. First, we can use the `cov` function to obtain the variance-covariance matrix. This matrix incorporates the variance of each variable on the diagonal and the covariances in the remaining cells. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#store covariances\ncov_mat <- cov(cbind(EP, SP, HP, DP, O1, O2, O3)) |> round(2)\n\n#Let's take a look\ncov_mat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      EP    SP    HP    DP    O1    O2    O3\nEP  0.51  0.26  0.28  0.20 -0.12 -0.12 -0.15\nSP  0.26  0.47  0.24  0.19 -0.11 -0.10 -0.12\nHP  0.28  0.24  2.44  0.20 -0.18 -0.22 -0.23\nDP  0.20  0.19  0.20  0.28 -0.08 -0.08 -0.09\nO1 -0.12 -0.11 -0.18 -0.08  0.23  0.15  0.18\nO2 -0.12 -0.10 -0.22 -0.08  0.15  0.22  0.17\nO3 -0.15 -0.12 -0.23 -0.09  0.18  0.17  0.26\n```\n\n\n:::\n:::\n\n\nThis works well as long as we have a data set (e.g., from a pilot study or published work) to estimate the variances and covariances. In other cases, however, we might not have access to such a data set. In this case, we might only have a correlation table that was provided in a published paper. But that's no problem either, as we can transform the correlations and standard deviations of the variables of interest into a variance-covariance matrix. The following chunk shows how this works by using the `cor2cov` function from the `MBESS` package. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#store correlation matrix\ncor_mat <- cor(cbind(EP, SP, HP, DP, O1, O2, O3))\n\n#store standard deviations\nsd_vector <- c(sd(EP), sd(SP), sd(HP), sd(DP), sd(O1), sd(O2), sd(O3))\n\n#transform correlations and standard deviations into variance-covariance matrix\ncov_mat2 <- MBESS::cor2cov(cor.mat = cor_mat, sd = sd_vector) |>\n  as.data.frame() |>\n  round(2)\n\n#Let's take a look\ncov_mat2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      EP    SP    HP    DP    O1    O2    O3\nEP  0.51  0.26  0.28  0.20 -0.12 -0.12 -0.15\nSP  0.26  0.47  0.24  0.19 -0.11 -0.10 -0.12\nHP  0.28  0.24  2.44  0.20 -0.18 -0.22 -0.23\nDP  0.20  0.19  0.20  0.28 -0.08 -0.08 -0.09\nO1 -0.12 -0.11 -0.18 -0.08  0.23  0.15  0.18\nO2 -0.12 -0.10 -0.22 -0.08  0.15  0.22  0.17\nO3 -0.15 -0.12 -0.23 -0.09  0.18  0.17  0.26\n```\n\n\n:::\n:::\n\n\nLet's do a plausibility check: Did the two ways to estimate the variance-covariance matrix lead to the same results?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncov_mat == cov_mat2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     EP   SP   HP   DP   O1   O2   O3\nEP TRUE TRUE TRUE TRUE TRUE TRUE TRUE\nSP TRUE TRUE TRUE TRUE TRUE TRUE TRUE\nHP TRUE TRUE TRUE TRUE TRUE TRUE TRUE\nDP TRUE TRUE TRUE TRUE TRUE TRUE TRUE\nO1 TRUE TRUE TRUE TRUE TRUE TRUE TRUE\nO2 TRUE TRUE TRUE TRUE TRUE TRUE TRUE\nO3 TRUE TRUE TRUE TRUE TRUE TRUE TRUE\n```\n\n\n:::\n:::\n\n\nIndeed, this worked! Both procedures lead to the exact same variance-covariance matrix. Now that we have an approximation of the variance-covariance matrix, we use the `rmvnorm` function from the `Rfast` package to simulate data from a multivariate normal distribution. The following code simulates `n = 50` observations from the specified population. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Set seed to make results reproducible\nset.seed(21364)\n\n#simulate data\nmy_first_simulated_data <- Rfast::rmvnorm(\n  n = 50,\n  mu = means_vector,\n  sigma = cov_mat\n) |>\n  as.data.frame()\n\n#Let's take a look\nhead(my_first_simulated_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        EP       SP         HP       DP       O1       O2       O3\n1 1.331159 1.690898 -0.2686425 1.281535 3.514007 3.297457 4.018206\n2 2.150835 2.069363  1.8537706 2.066787 3.830672 3.845564 3.777120\n3 2.440606 2.377261  0.2257497 2.325096 3.895984 3.220516 3.857794\n4 3.621513 2.197040  2.1446018 3.508653 4.080440 3.746210 4.132182\n5 2.124958 2.037299  1.7958220 2.028219 3.214294 3.045947 3.479226\n6 2.404379 2.758697  1.4287525 2.192714 3.967533 3.739506 3.652799\n```\n\n\n:::\n:::\n\n\nWe could now fit a SEM to this simulated data set and check whether the regression coefficient modelling the association between openness to experience and generalized prejudice is significant at an $\\alpha$-level of .005. We will work with the `lavaan` package to fit SEMs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#specify SEM\nmodel_sem <- \"generalized_prejudice =~ EP + DP + SP + HP\n              openness =~ O1 + O2 + O3\n              generalized_prejudice ~ openness\"\n\n#fit the SEM to the simulated data set\nfit_sem <- sem(model_sem, data = my_first_simulated_data)\n\n#display the results\nsummary(fit_sem)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.7-2 ended normally after 36 iterations\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                        15\n\n  Number of observations                            50\n\nModel Test User Model:\n                                                      \n  Test statistic                                 5.638\n  Degrees of freedom                                13\n  P-value (Chi-square)                           0.958\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nLatent Variables:\n                           Estimate  Std.Err  z-value  P(>|z|)\n  generalized_prejudice =~                                    \n    EP                        1.000                           \n    DP                        0.492    0.087    5.629    0.000\n    SP                        0.621    0.118    5.261    0.000\n    HP                        0.572    0.262    2.185    0.029\n  openness =~                                                 \n    O1                        1.000                           \n    O2                        1.023    0.153    6.665    0.000\n    O3                        0.992    0.160    6.219    0.000\n\nRegressions:\n                          Estimate  Std.Err  z-value  P(>|z|)\n  generalized_prejudice ~                                    \n    openness                -0.979    0.310   -3.158    0.002\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)\n   .EP                0.082    0.074    1.107    0.268\n   .DP                0.118    0.030    3.956    0.000\n   .SP                0.242    0.057    4.263    0.000\n   .HP                1.771    0.358    4.941    0.000\n   .O1                0.076    0.021    3.635    0.000\n   .O2                0.038    0.016    2.315    0.021\n   .O3                0.074    0.020    3.635    0.000\n   .generlzd_prjdc    0.464    0.128    3.613    0.000\n    openness          0.144    0.044    3.304    0.001\n```\n\n\n:::\n:::\n\n\nThe results show that in this case, the regression coefficient is -0.98 which is significant with p = 0.002. But, actually, it is not our primary interest to see whether this particular simulated data set results in a significant regression coefficient. Rather, we want to know how many of a theoretically infinite number of simulations yield a significant p-value of the focal regression coefficient. Thus, as in the previous chapters, we now repeatedly simulate data sets of a certain size (say, 50 observations) from the specified population and store the results of the focal test (here: the p-value of the regression coefficient) in a vector called `p_values`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Set seed to make results reproducible\nset.seed(21364)\n\n#let's do 500 iterations\niterations <- 500\n\n#prepare an empty NA vector with 500 slots\np_values <- rep(NA, iterations)\n\n#sample size per iteration\nn <- 50\n\n\n#simulate data\nfor (i in 1:iterations) {\n  simulated_data <- Rfast::rmvnorm(n = n, mu = means_vector, sigma = cov_mat) |>\n    as.data.frame()\n  fit_sem_simulated <- sem(model_sem, data = simulated_data)\n\n  p_values[i] <- parameterestimates(fit_sem_simulated)[8, ]$pvalue\n}\n```\n:::\n\n\nHow many of our 500 virtual samples would have found a significant p-value (i.e., p < .005)?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#frequency table\ntable(p_values < .005)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE \n  152   348 \n```\n\n\n:::\n\n```{.r .cell-code}\n#percentage of significant results\nsum(p_values < .005) / iterations * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 69.6\n```\n\n\n:::\n:::\n\n\nOnly 69.6% of samples with the same size of $n=50$ result in a significant p-value. We conclude that $n=50$ observations seems to be insufficient, as the power with these parameters is lower than 80%. \n\n## Sample size planning: Find the necessary sample size\n\nBut how many observations do we need to find the presumed effect with a power of 80%? Like before, we can now systematically vary certain parameters (e.g., sample size) of our simulation and see how that affects power. We could, for example, vary the sample size in a range from 30 to 200. Running these simulations typically requires quite some computing time.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Set seed to make results reproducible\nset.seed(21364)\n\n#test ns between 30 and 200\nns_sem <- seq(30, 200, by = 10)\n\n#prepare empty vector to store results\nresult_sem <- data.frame()\n\n#set number of iterations\niterations_sem <- 500\n\n#write function\nsim_sem <- function(n, model, mu, sigma) {\n  simulated_data <- Rfast::rmvnorm(n = n, mu = mu, sigma = sigma) |>\n    as.data.frame()\n  fit_sem_simulated <- sem(model, data = simulated_data)\n  p_value_sem <- parameterestimates(fit_sem_simulated)[8, ]$pvalue\n  return(p_value_sem)\n}\n\n\n#replicate function with varying ns\nfor (n in ns_sem) {\n  p_values_sem <- future_replicate(\n    iterations_sem,\n    sim_sem(n = n, model = model_sem, mu = means_vector, sigma = cov_mat),\n    future.seed = TRUE\n  )\n  result_sem <- rbind(\n    result_sem,\n    data.frame(\n      n = n,\n      power = sum(p_values_sem < .005) / iterations_sem\n    )\n  )\n\n  #The following line of code can be used to track the progress of the simulations\n  #This can be helpful for simulations with a high number of iterations and/or a large parameter space which require a lot of time\n  #I have deactivated this here; to enable it, just remove the \"#\" sign at the beginning of the next line\n  #message(paste(\"Progress info: Simulations completed for n =\", n))\n}\n```\n:::\n\n\nLet's plot the results:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(result_sem, aes(x = n, y = power)) +\n  geom_point() +\n  geom_line() +\n  scale_x_continuous(n.breaks = 18, limits = c(30, 200)) +\n  scale_y_continuous(n.breaks = 10, limits = c(0, 1)) +\n  geom_hline(yintercept = 0.8, color = \"red\")\n```\n\n::: {.cell-output-display}\n![](sem_files/figure-html/plot power curve SEM-1.png){width=672}\n:::\n:::\n\n\nThis graph suggests that we need a sample size of approximately 50 participants to reach a power of 80% with the given population estimates. That's all it takes to run a power analysis for a SEM! \n\nIn the following two sub-paragraphs, we would like to present two alternatives and/or extensions to this first way of doing a power analysis for a SEM. First, we would like to present an alternative way to simulate data for SEMs, i.e., by using a built-in function in the `lavaan` package. Second, we would like to show how a \"safeguard\" approach to power analysis can be used within the context of SEM.\n\n## Using the lavaan syntax to simulate data\n\nIn our opening example in this chapter, we used the `rmvnorm` function from the `Rfast`package to simulate data based on the means of the manifest variables as well as their variance-covariance matrix. An alternative to this procedure is to use a built-in function in the `lavaan` package, that is, the `simulateData()` function. The main idea here is to provide this function with a lavaan model that specifies all relevant population parameters and then to use this function to directly simulate data. \n\nMore specifically, we need to incorporate the factor loadings, regression coefficients and (residual) variances of all latent and manifest variables in the lavaan syntax. As these parameters are hardly ever known without a previous study, we will again draw on the results from the data by Bergh et al. (2016). Let's again take a look at the results of our SEM when applying it to this data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#fit the SEM to the pilot data set\nfit_bergh <- sem(model_sem, data = Bergh)\n\n#display the results\nsummary(fit_bergh)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.7-2 ended normally after 40 iterations\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                        15\n\n  Number of observations                           861\n\nModel Test User Model:\n                                                      \n  Test statistic                                40.574\n  Degrees of freedom                                13\n  P-value (Chi-square)                           0.000\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nLatent Variables:\n                           Estimate  Std.Err  z-value  P(>|z|)\n  generalized_prejudice =~                                    \n    EP                        1.000                           \n    DP                        0.710    0.041   17.383    0.000\n    SP                        0.907    0.052   17.337    0.000\n    HP                        1.042    0.112    9.267    0.000\n  openness =~                                                 \n    O1                        1.000                           \n    O2                        0.932    0.035   26.255    0.000\n    O3                        1.143    0.040   28.923    0.000\n\nRegressions:\n                          Estimate  Std.Err  z-value  P(>|z|)\n  generalized_prejudice ~                                    \n    openness                -0.766    0.056  -13.641    0.000\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)\n   .EP                0.219    0.016   13.403    0.000\n   .DP                0.141    0.009   14.972    0.000\n   .SP                0.233    0.015   15.079    0.000\n   .HP                2.124    0.106   19.965    0.000\n   .O1                0.073    0.005   14.423    0.000\n   .O2                0.079    0.005   15.805    0.000\n   .O3                0.052    0.005    9.823    0.000\n   .generlzd_prjdc    0.191    0.018   10.362    0.000\n    openness          0.161    0.011   14.210    0.000\n```\n\n\n:::\n:::\n\n\nIn order to use the `simulateData()` function, we can take the estimates from this previous study and plug them into the lavaan syntax in the following chunk. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Set seed to make results reproducible\nset.seed(21364)\n\n#specify SEM\nmodel_fully_specified <-\n  \"generalized_prejudice =~ 1*EP + 0.71*DP + 0.91*SP + 1*HP\nopenness =~ 1*O1 + 0.93*O2 + 1.14*O3\ngeneralized_prejudice ~ -0.77*openness\n\n\ngeneralized_prejudice ~~ 0.19*generalized_prejudice\nopenness ~~ 0.16*openness\nEP ~~ 0.21*EP\nDP ~~ 0.14*DP\nSP ~~ 0.23*SP\nHP ~~ 2.12*HP\nO1 ~~ 0.07*O1\nO2 ~~ 0.08*O2\nO3 ~~ 0.05*O3\n\n\"\n\n#lets try this\nsim_lavaan <- simulateData(model_fully_specified, sample.nobs = 100)\nhead(sim_lavaan)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            EP         DP          SP         HP          O1         O2\n1  0.009175975 -0.4818076 -0.29785829 -3.5273250 -0.02254289 -0.1394437\n2 -0.204483904 -0.4787598  0.15013918 -3.1894504 -0.56917823 -0.2076622\n3  0.456774325 -0.6544974  0.05802164 -2.3337546  0.26092341  0.7767911\n4 -1.153264826 -0.3216415 -0.91603659 -2.0334785 -0.16649019 -0.1387532\n5  0.512683482  0.3138148  0.28465681  0.1202821 -0.41602783 -0.2699893\n6 -1.064347791 -0.3287166 -0.62215235 -2.4007914  0.60927732 -0.1814121\n           O3\n1 -0.22583796\n2 -1.17504320\n3  0.11402119\n4  0.06726909\n5 -0.62531893\n6  0.13393737\n```\n\n\n:::\n:::\n\n\nThe next step is to integrate this code into our first simulation-based power analysis in this chapter, that is, to replace the data simulation process using the `rmvnorm` function from the `Rfast` package with this new method using `simulateData()` from the `lavaan` package. To this end, I am adapting the `power analysis SEM` chunk from above accordingly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Set seed to make results reproducible\nset.seed(21364)\n\n#test ns between 30 and 200\nns_sem <- seq(30, 200, by = 10)\n\n#prepare empty vector to store results\nresult_sem <- data.frame()\n\n#set number of iterations\niterations_sem <- 500\n\n#write function\nsim_sem_lavaan <- function(n, model) {\n  sim_lavaan <- simulateData(model = model, sample.nobs = n)\n  fit_sem_simulated <- sem(model_sem, data = sim_lavaan)\n  p_value_sem <- parameterestimates(fit_sem_simulated)[8, ]$pvalue\n  return(p_value_sem)\n}\n\n\n#replicate function with varying ns\nfor (n in ns_sem) {\n  p_values_sem <- future_replicate(\n    iterations_sem,\n    sim_sem_lavaan(n = n, model = model_fully_specified),\n    future.seed = TRUE\n  )\n  result_sem <- rbind(\n    result_sem,\n    data.frame(\n      n = n,\n      power = sum(p_values_sem < .005, na.rm = TRUE) / iterations_sem\n    )\n  )\n\n  #The following line of code can be used to track the progress of the simulations\n  #This can be helpful for simulations with a high number of iterations and/or a large parameter space which require a lot of time\n  #I have deactivated this here; to enable it, just remove the \"#\" sign at the beginning of the next line\n  #message(paste(\"Progress info: Simulations completed for n =\", n))\n}\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nlavaan NOTE:  \n   the model with the switched marker item(s) did not converge; reverting to \n   the original marker item(s).\n```\n\n\n:::\n:::\n\n\nLet's plot this again. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(result_sem, aes(x = n, y = power)) +\n  geom_point() +\n  geom_line() +\n  scale_x_continuous(n.breaks = 18, limits = c(30, 200)) +\n  scale_y_continuous(n.breaks = 10, limits = c(0, 1)) +\n  geom_hline(yintercept = 0.8, color = \"red\")\n```\n\n::: {.cell-output-display}\n![](sem_files/figure-html/plot power curve SEM lavaan-1.png){width=672}\n:::\n:::\n\n\nHere, we conclude that approx. 55 participants would be needed to achieve 80% power. The slight difference compared to the previous power analysis should be explained by the fact that we rounded the numbers that define our statistical populations and that we only used 500 Monte Carlo iterations -- these differences should decrease with an increasing number of iterations.  \n\n::: {.callout-tip}\n\nWang and Rhemtulla ([2021](https://doi.org/10.1177/2515245920918253)) developed a shiny app that can do power analyses for SEMs in a similar fashion, but that additionally provides a point-and-click interface. You can use it here, for instance, to replicate the results of this simulation-based power analysis: [https://yilinandrewang.shinyapps.io/pwrSEM/](https://yilinandrewang.shinyapps.io/pwrSEM/). \n\n:::\n\n## A safeguard power approach for SEMs\n\nOf note, the two power analyses for our SEM we have conducted so far used the observed effect size from the Bergh et al. (2016) data set as an estimate of the \"true\" effect size. But, as this point estimate may be imprecise (e.g., because of publication bias), it seems reasonable to use a more conservative estimate of the true effect size. One more conservative approach in this context is the safeguard power approach (Perugini et al., [2014](https://doi.org/10.1177/1745691614528519)), which we have already applied in Chapter 1 ([Linear Model 1: A single dichotomous predictor](lm1.qmd)).\n\nBasically, all need to do in order to account for variability of observed effect sizes is to calculate a 60%-confidence interval around the point estimate of the observed effect size from our pilot data and to use the more conservative bound of this confidence interval (here: the upper bound) as our new effect size estimate. This can be easily done with the `parameterestimates` function from the `lavaan` package which takes the level of the confidence interval as an input parameter. Let's use this function on our object `fit_bergh` which stores the results of our SEM in the `Bergh` data set.  \n\n\n::: {.cell}\n\n```{.r .cell-code}\nparameterestimates(fit_bergh, level = .60)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     lhs op                   rhs    est    se       z pvalue\n1  generalized_prejudice =~                    EP  1.000 0.000      NA     NA\n2  generalized_prejudice =~                    DP  0.710 0.041  17.383      0\n3  generalized_prejudice =~                    SP  0.907 0.052  17.337      0\n4  generalized_prejudice =~                    HP  1.042 0.112   9.267      0\n5               openness =~                    O1  1.000 0.000      NA     NA\n6               openness =~                    O2  0.932 0.035  26.255      0\n7               openness =~                    O3  1.143 0.040  28.923      0\n8  generalized_prejudice  ~              openness -0.766 0.056 -13.641      0\n9                     EP ~~                    EP  0.219 0.016  13.403      0\n10                    DP ~~                    DP  0.141 0.009  14.972      0\n11                    SP ~~                    SP  0.233 0.015  15.079      0\n12                    HP ~~                    HP  2.124 0.106  19.965      0\n13                    O1 ~~                    O1  0.073 0.005  14.423      0\n14                    O2 ~~                    O2  0.079 0.005  15.805      0\n15                    O3 ~~                    O3  0.052 0.005   9.823      0\n16 generalized_prejudice ~~ generalized_prejudice  0.191 0.018  10.362      0\n17              openness ~~              openness  0.161 0.011  14.210      0\n   ci.lower ci.upper\n1     1.000    1.000\n2     0.676    0.744\n3     0.863    0.951\n4     0.948    1.137\n5     1.000    1.000\n6     0.902    0.962\n7     1.110    1.176\n8    -0.814   -0.719\n9     0.205    0.233\n10    0.133    0.148\n11    0.220    0.246\n12    2.034    2.213\n13    0.069    0.078\n14    0.074    0.083\n15    0.048    0.057\n16    0.175    0.206\n17    0.152    0.171\n```\n\n\n:::\n:::\n\n\nThis output shows that the upper bound of the 60% confidence interval around the focal regression coefficient is -0.72. We can now use this as our new and more conservative effect size estimate. We can for example insert this value into our simulation using the lavaan syntax. For this purpose, we copy the chunk from above and simply replace the previous effect size estimate (-0.77) with the new estimate (-0.72), while keeping all other parameters that define this data set. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Set seed to make results reproducible\nset.seed(21364)\n\n#specify SEM\nmodel_fully_specified_safeguard <-\n  \"generalized_prejudice =~ 1*EP + 0.71*DP + 0.91*SP + 1*HP\nopenness =~ 1*O1 + 0.93*O2 + 1.14*O3\ngeneralized_prejudice ~ -0.72*openness\n\n\ngeneralized_prejudice ~~ 0.19*generalized_prejudice\nopenness ~~ 0.16*openness\nEP ~~ 0.21*EP\nDP ~~ 0.14*DP\nSP ~~ 0.23*SP\nHP ~~ 2.12*HP\nO1 ~~ 0.07*O1\nO2 ~~ 0.08*O2\nO3 ~~ 0.05*O3\n\n\"\n\n#lets try this\nsim_lavaan_safeguard <- simulateData(\n  model_fully_specified_safeguard,\n  sample.nobs = 100\n)\nhead(sim_lavaan_safeguard)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           EP         DP         SP         HP          O1         O2\n1  0.03163582 -0.4674398 -0.2762416 -3.5075535 -0.04391145 -0.1593227\n2 -0.19674199 -0.4764434  0.1605740 -3.1573002 -0.58997086 -0.2268869\n3  0.48315832 -0.6351419  0.0799879 -2.3272372  0.25229795  0.7683784\n4 -1.13893054 -0.3131634 -0.9001980 -2.0386232 -0.18372798 -0.1543441\n5  0.49985196  0.3039113  0.2740270  0.1386227 -0.41638579 -0.2703941\n6 -1.04098556 -0.3130325 -0.5996895 -2.4067345  0.59293247 -0.1965773\n           O3\n1 -0.25024294\n2 -1.19986667\n3  0.10431698\n4  0.04700113\n5 -0.62587386\n6  0.11528181\n```\n\n\n:::\n:::\n\n\nNow, everything is ready for the actual safeguard power analysis. We can re-use the `sim_sem_lavaan` function we have defined above. Let's see what we get here! \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Set seed to make results reproducible\nset.seed(21364)\n\n#prepare empty vector to store results\nresult_sem_safeguard <- data.frame()\n\n#replicate function with varying ns\nfor (n in ns_sem) {\n  p_values_sem_safeguard <- future_replicate(\n    iterations_sem,\n    sim_sem_lavaan(n = n, model = model_fully_specified_safeguard),\n    future.seed = TRUE\n  )\n  result_sem_safeguard <- rbind(\n    result_sem_safeguard,\n    data.frame(\n      n = n,\n      power = sum(p_values_sem_safeguard < .005, na.rm = TRUE) / iterations_sem\n    )\n  )\n\n  #The following line of code can be used to track the progress of the simulations\n  #This can be helpful for simulations with a high number of iterations and/or a large parameter space which require a lot of time\n  #I have deactivated this here; to enable it, just remove the \"#\" sign at the beginning of the next line\n  #message(paste(\"Progress info: Simulations completed for n =\", n))\n}\n\nggplot(result_sem_safeguard, aes(x = n, y = power)) +\n  geom_point() +\n  geom_line() +\n  scale_x_continuous(n.breaks = 18, limits = c(30, 200)) +\n  scale_y_continuous(n.breaks = 10, limits = c(0, 1)) +\n  geom_hline(yintercept = 0.8, color = \"red\")\n```\n\n::: {.cell-output-display}\n![](sem_files/figure-html/safeguard power analysis-1.png){width=672}\n:::\n:::\n\nThis safeguard power analysis yields a required sample size of ca. 63 participants.\n\n::: {.callout-note}\n\nIn addition to this safeguard power approach, we would also have liked to derive a smallest effect size of interest (SESOI). However, no prior studies on SESOI in the context of personality/stereotypes were available and the measures/response scales used by Bergh et al. (2016) were only vaguely reported in their manuscript, thereby making it difficult to derive a meaningful SESOI. We therefore only report a safeguard approach but no SESOI approach here.\n\n:::\n\n# A simulation-based power analysis for a mediation model with latent variables\n\nSometimes, researchers not only wish to investigate whether and how two (latent) variables related to each other, but also whether the association between two (manifest or latent) variables is mediated by a third variable. We will run a power analysis for such a latent mediation model, investigating whether gender affects generalized prejudice (fully or partially) through openness to experience, while using the Bergh et al. (2016) data set as a pilot study. We can repeat the same steps as in our previous power analysis, while incorporating gender into our analysis. Specifically, we will follow these steps:\n\n1. find plausible estimates of the population parameters\n2. specify the statistical model\n3. simulate data from this population\n4. compute the index of interest (e.g., the p-value) and store the results\n5. repeat steps 2) and 3) multiple times\n6. count how many samples would have detected the specified effect (i.e., compute the statistical power)\n7. vary your simulation parameters until the desired level of power (e.g., 80%) is achieved\n\nWe first draw on the Bergh et al. (2016) data set to estimate the means and the variance-covariance matrix. In this data set, gender is a factor with two levels, male and female. We first need to transform this categorical variable into an integer variable, for instance coding \"male\" with 0 and \"female\" with 1. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nBergh_int <- Bergh\nBergh_int$gender <- ifelse(\n  Bergh_int$gender == \"male\",\n  0,\n  ifelse(Bergh_int$gender == \"female\", 1, NA)\n)\n\nattach(Bergh_int)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from Bergh:\n\n    A1, A2, A3, DP, EP, gender, HP, O1, O2, O3, SP\n```\n\n\n:::\n\n```{.r .cell-code}\n#store means\nmeans_mediation <- c(\n  mean(gender),\n  mean(EP),\n  mean(SP),\n  mean(HP),\n  mean(DP),\n  mean(O1),\n  mean(O2),\n  mean(O3)\n) |>\n  round(2)\n\n#store covarainces\ncov_mediation <- cov(cbind(gender, EP, SP, HP, DP, O1, O2, O3)) |> round(2)\n```\n:::\n\n\n::: {.callout-tip}\n\nIf we were  interested in a mediation model with only manifest variables, we could also use a useful shiny app developed by Schoemann et al. (2017), which can be accessed via [https://schoemanna.shinyapps.io/mc_power_med/](https://schoemanna.shinyapps.io/mc_power_med/). This app currently enables power analyses for some manifest mediation models: mediation with (i) one mediator, (ii) two parallel mediators, (iii) two serial mediators, and (iv) three parallel mediators. But as we want to incorporate `generalized prejudice` and `openness to experience` as latent variables, we need to write a simulation-based power analyses ourselves.   \n\n:::\n\n\nNow, we specify the statistical mediation model in `lavaan`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#specify mediation model\nmodel_mediation <- '\n\n              # measurement model\n              generalized_prejudice =~ EP + DP + SP + HP\n              openness =~ O1 + O2 + O3\n              \n              # direct effect\n              generalized_prejudice ~ c*gender\n              \n              # mediator\n              openness ~ a*gender\n              generalized_prejudice ~ b*openness\n\n              # indirect effect (a*b)\n              ab := a*b\n           \n              # total effect\n              total := c + (a*b)\n\n'\n```\n:::\n\n\nTo verify that this model syntax works properly, we can fit this model to the data set provided by Bergh et al. (2016).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#fit the SEM to the simulated data set\nfit_mediation <- sem(model_mediation, data = Bergh_int)\n\n#display the results\nsummary(fit_mediation)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.7-2 ended normally after 39 iterations\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                        17\n\n  Number of observations                           861\n\nModel Test User Model:\n                                                      \n  Test statistic                                84.622\n  Degrees of freedom                                18\n  P-value (Chi-square)                           0.000\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nLatent Variables:\n                           Estimate  Std.Err  z-value  P(>|z|)\n  generalized_prejudice =~                                    \n    EP                        1.000                           \n    DP                        0.723    0.042   17.332    0.000\n    SP                        0.962    0.054   17.722    0.000\n    HP                        1.057    0.115    9.174    0.000\n  openness =~                                                 \n    O1                        1.000                           \n    O2                        0.931    0.035   26.266    0.000\n    O3                        1.142    0.039   28.923    0.000\n\nRegressions:\n                          Estimate  Std.Err  z-value  P(>|z|)\n  generalized_prejudice ~                                    \n    gender     (c)          -0.268    0.039   -6.815    0.000\n  openness ~                                                 \n    gender     (a)           0.094    0.032    2.950    0.003\n  generalized_prejudice ~                                    \n    openness   (b)          -0.712    0.054  -13.245    0.000\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)\n   .EP                0.233    0.016   14.383    0.000\n   .DP                0.142    0.009   15.316    0.000\n   .SP                0.217    0.015   14.405    0.000\n   .HP                2.130    0.106   20.005    0.000\n   .O1                0.073    0.005   14.395    0.000\n   .O2                0.079    0.005   15.798    0.000\n   .O3                0.052    0.005    9.855    0.000\n   .generlzd_prjdc    0.168    0.017   10.051    0.000\n   .openness          0.160    0.011   14.210    0.000\n\nDefined Parameters:\n                   Estimate  Std.Err  z-value  P(>|z|)\n    ab               -0.067    0.023   -2.891    0.004\n    total            -0.335    0.044   -7.552    0.000\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nlavaan NOTE:  \n   Standard errors and confidence intervals of the (nonlinear) defined (:=) \n   parameters are based on the first-order delta method; for strongly \n   nonlinear definitions, se.def = \"mc\" (Monte Carlo) or se = \"bootstrap\" may \n   be more accurate.\n```\n\n\n:::\n:::\n\n\nNow, everything is set up to run the actual power analysis. In the following chunk, we repeatedly simulate data from the specified population and store the p-value of the indirect effect while varying the sample size in a range from 500 to 1500. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Set seed to make results reproducible\nset.seed(21364)\n\n#test ns between 100 and 1500\nns_mediation <- seq(500, 1500, by = 50)\n\n#prepare empty vector to store results\nresult_mediation <- data.frame()\n\n#iterations\niterations_mediation <- 500\n\n#write function\nsim_mediation <- function(n, model, mu, sigma) {\n  simulated_data_mediation <- Rfast::rmvnorm(n = n, mu = mu, sigma = sigma) |>\n    as.data.frame()\n  fit_mediation_simulated <- sem(model, data = simulated_data_mediation)\n\n  p_value_mediation <- parameterestimates(fit_mediation_simulated)[21, ]$pvalue\n  return(p_value_mediation)\n}\n\n\n#replicate function with varying ns\nfor (n in ns_mediation) {\n  p_values_mediation <- future_replicate(\n    iterations_mediation,\n    sim_mediation(\n      n = n,\n      model = model_mediation,\n      mu = means_mediation,\n      sigma = cov_mediation\n    ),\n    future.seed = TRUE\n  )\n  result_mediation <- rbind(\n    result_mediation,\n    data.frame(\n      n = n,\n      power = sum(p_values_mediation < .005) / iterations_mediation\n    )\n  )\n\n  #The following line of code can be used to track the progress of the simulations\n  #This can be helpful for simulations with a high number of iterations and/or a large parameter space which require a lot of time\n  #I have deactivated this here; to enable it, just remove the \"#\" sign at the beginning of the next line\n  #message(paste(\"Progress info: Simulations completed for n =\", n))\n}\n```\n:::\n\n\nLet's plot the results:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(result_mediation, aes(x = n, y = power)) +\n  geom_point() +\n  geom_line() +\n  scale_y_continuous(n.breaks = 10) +\n  scale_x_continuous(n.breaks = 20) +\n  geom_hline(yintercept = 0.8, color = \"red\")\n```\n\n::: {.cell-output-display}\n![](sem_files/figure-html/plot power curve mediation-1.png){width=672}\n:::\n:::\n\n\nThis shows that roughly 1,300 to 1,400 participants will be needed to obtain sufficient power under the assumptions we specified. To achieve a more precise estimate, just increase the number of iterations (and get a cup of coffee while you wait for the results 😅). \n\n# References\n\nBergh, R., Akrami, N., Sidanius, J., & Sibley, C. G. (2016). Is group membership necessary for understanding generalized prejudice? A re-evaluation of why prejudices are interrelated. Journal of Personality and Social Psychology, 111(3), 367–395. [https://doi.org/10.1037/pspi0000064](https://www.researchgate.net/publication/306939541_Is_group_membership_necessary_for_understanding_generalized_prejudice_A_re-evaluation_of_why_prejudices_are_interrelated)\n\nPerugini, M., Gallucci, M., & Costantini, G. (2014). Safeguard power as a protection against imprecise power estimates. Perspectives on Psychological Science, 9(3), 319--332. <https://doi.org/10.1177/1745691614528519>\n\nSchoemann, A. M., Boulton, A. J., & Short, S. D. (2017). Determining power and sample size for simple and complex mediation models. Social Psychological and Personality Science, 8(4), 379–386. [https://doi.org/10.1177/1948550617715068](https://www.researchgate.net/publication/317631067_Determining_Power_and_Sample_Size_for_Simple_and_Complex_Mediation_Models)\n\nWang, Y. A., & Rhemtulla, M. (2021). Power analysis for parameter estimation in structural equation modeling: A discussion and tutorial. Advances in Methods and Practices in Psychological Science, 4(1), 1–17. [https://doi.org/10.1177/2515245920918253](https://doi.org/10.1177/2515245920918253)\n\n",
    "supporting": [
      "sem_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}